export const initialBrands = [
  { name: 'Bazooka', color: '#00aeef', svgType: 'bazooka' },
  { name: 'Chupa Chups', color: '#e20613', svgType: 'chupachups' },
  { name: 'Hershey\'s', color: '#2a120e', svgType: 'hersheys' },
  { name: 'Reeses', color: '#f05a28', svgType: 'reeses' },
  { name: 'Walkers', color: '#ffffff', svgType: 'walkers' },
  { name: 'Warheads', color: '#4a2c81', svgType: 'warheads' }
];

export const defaultUsers = [
  { name: 'Sarah Jenkins', email: 'sarah.j@gmail.com', password: 'password123', role: 'user' },
  { name: 'Matthew Taylor', email: 'matthew.t@hotmail.co.nz', password: 'password123', role: 'user' },
  { name: 'Chloe Smith', email: 'chloe.s@gmail.com', password: 'password123', role: 'user' },
  { name: 'Liam Wilson', email: 'liam.wilson@yahoo.com', password: 'password123', role: 'user' },
  { name: 'Store Administrator', email: 'admin@lollyshop.co.nz', password: 'admin123', role: 'admin' },
  { name: 'John Doe', email: 'john@gmail.com', password: 'user123', role: 'user' }
];

export const initialProducts = [
  {
    id: "p-glo-hearts",
    name: 'GLO HEARTS (MAYCEYS)',
    category: 'Hard Lollies',
    mainCategory: 'NZ Lollies',
    price: 15.99,
    rating: 5.0,
    reviewsCount: 48,
    description: "Mayceys Glo Hearts are iconic New Zealand hard candy hearts with a bright, sweet fruit flavor! Perfect for parties, weddings, Valentine's, and special occasions.",
    ingredients: 'Sugar, Glucose Syrup, Water, Food Acid (Citric Acid), Flavors, Colors (124).',
    nutrition: { calories: '145 kcal', sugar: '28g', fat: '0g', protein: '0g' },
    gradient: 'linear-gradient(135deg, #FF0055 0%, #FF66B2 100%)',
    image: 'https://images.unsplash.com/photo-1582293041079-7814c2f12063?auto=format&fit=crop&q=80&w=600',
    images: ['https://images.unsplash.com/photo-1582293041079-7814c2f12063?auto=format&fit=crop&q=80&w=600'],
    inStock: true,
    quantity: 100,
    isPopular: true,
    isNew: true,
    collections: ['Parties', 'Weddings', 'Valentine', 'Halloween', 'Christmas', 'Birthdays', 'Gifts', 'NZFavourites', 'KiwiFavourites', 'NZLollies', 'KiwiLollies', 'NZCandy', 'KiwiClassics', 'Mayceys', 'Sweet Lollies']
  },
  {
    id: "p-jersey-caramel",
    name: 'JERSEY CARAMEL',
    category: 'Hard Lollies',
    mainCategory: 'NZ Lollies',
    price: 13.99,
    rating: 4.9,
    reviewsCount: 36,
    description: 'Classic Jersey Caramel lollies featuring smooth, rich caramel layers with a soft fudge center. A timeless Kiwi candy classic loved by generations!',
    ingredients: 'Sugar, Glucose Syrup, Condensed Milk, Vegetable Oil, Wheat Flour, Caramel Flavor, Salt.',
    nutrition: { calories: '160 kcal', sugar: '24g', fat: '4.5g', protein: '1.2g' },
    gradient: 'linear-gradient(135deg, #D4A373 0%, #FAEDCD 100%)',
    image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&q=80&w=600',
    images: ['https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&q=80&w=600'],
    inStock: true,
    quantity: 100,
    isPopular: true,
    isNew: false,
    collections: ['Parties', 'Weddings', 'Halloween', 'Christmas', 'Birthdays', 'Gifts', 'Kids', 'NZ Favourites', 'Kiwi Favourites', 'Sweet Lollies']
  },
  {
    id: "p-fizzers",
    name: 'FIZZERS',
    category: 'Sour Lollies',
    mainCategory: 'NZ Lollies',
    price: 0.99,
    rating: 4.8,
    reviewsCount: 52,
    description: 'Tangy, mouth-watering sour fizzy candy rolls! Packed with fruity flavor and an electrifying fizz in every bite.',
    ingredients: 'Sugar, Acidity Regulators (Malic Acid, Tartaric Acid), Sodium Bicarbonate, Glucose Syrup, Flavors, Colors.',
    nutrition: { calories: '95 kcal', sugar: '21g', fat: '0g', protein: '0g' },
    gradient: 'linear-gradient(135deg, #11998e 0%, #38ef7d 100%)',
    image: 'https://images.unsplash.com/photo-1600431521340-491eca880813?auto=format&fit=crop&q=80&w=600',
    images: ['https://images.unsplash.com/photo-1600431521340-491eca880813?auto=format&fit=crop&q=80&w=600'],
    inStock: true,
    quantity: 100,
    isPopular: true,
    isNew: false,
    collections: ['NZ Favourites', 'kiwis Favourites', 'Parties', 'Weddings', 'Halloween', 'Christmas', 'Birthdays', 'Gifts', 'Kids']
  },
  {
    id: "p-rainbow-sour-belts",
    name: "RAINBOW SOUR BELTS",
    category: "Sour Lollies",
    mainCategory: "Imported Lollies",
    price: 4.99,
    rating: 4.9,
    reviewsCount: 64,
    description: "Multi-colored fizzy sour belts packed with strawberry, apple, blue raspberry and lemon flavor. Ultra chewy and delightfully sour!",
    ingredients: "Sugar, Glucose-Fructose Syrup, Wheat Flour, Malic Acid, Dextrose, Palm Oil, Citric Acid, Flavoring, Colors.",
    nutrition: { calories: "130 kcal", sugar: "26g", fat: "0.5g", protein: "1g" },
    gradient: "linear-gradient(135deg, #FF3366 0%, #FF9933 100%)",
    image: "https://images.unsplash.com/photo-1581798459219-318e76aecc7b?auto=format&fit=crop&q=80&w=600",
    images: ["https://images.unsplash.com/photo-1581798459219-318e76aecc7b?auto=format&fit=crop&q=80&w=600"],
    inStock: true,
    quantity: 80,
    isPopular: true,
    isNew: true,
    collections: ["Parties", "Kids", "TikTok Viral", "Sour Lollies", "Trending"]
  },
  {
    id: "p-gummy-bears-assorted",
    name: "FRUIT GUMMY BEARS NZ",
    category: "Gummies",
    mainCategory: "NZ Lollies",
    price: 3.99,
    rating: 4.9,
    reviewsCount: 89,
    description: "Classic chewy fruit gummy bears with 12 distinct real fruit juice flavours. Soft, bouncy texture bursting with sweet juiciness.",
    ingredients: "Glucose Syrup, Sugar, Gelatine, Dextrose, Fruit Juices from Concentrate, Citric Acid, Fruit and Plant Concentrates.",
    nutrition: { calories: "140 kcal", sugar: "22g", fat: "0.1g", protein: "2.5g" },
    gradient: "linear-gradient(135deg, #00f2fe 0%, #4facfe 100%)",
    image: "https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?auto=format&fit=crop&q=80&w=600",
    images: ["https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?auto=format&fit=crop&q=80&w=600"],
    inStock: true,
    quantity: 150,
    isPopular: true,
    isNew: false,
    collections: ["Kids", "Parties", "Birthdays", "Gummies", "NZ Favourites"]
  },
  {
    id: "p-belgian-chocolate-truffles",
    name: "BELGIAN DARK CHOCOLATE TRUFFLES",
    category: "Chocolates",
    mainCategory: "Chocolates",
    price: 12.99,
    rating: 5.0,
    reviewsCount: 42,
    description: "Rich artisanal 70% dark Belgian cocoa truffles dusted in fine Dutch cocoa powder. Melt-in-your-mouth luxury chocolate decadence.",
    ingredients: "Cocoa Mass, Sugar, Cocoa Butter, Butter Oil (Milk), Cocoa Powder, Emulsifier (Soy Lecithin), Natural Vanilla.",
    nutrition: { calories: "210 kcal", sugar: "16g", fat: "14g", protein: "3g" },
    gradient: "linear-gradient(135deg, #4A0E17 0%, #0F0C1B 100%)",
    image: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&q=80&w=600",
    images: ["https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&q=80&w=600"],
    inStock: true,
    quantity: 60,
    isPopular: true,
    isNew: true,
    collections: ["Gifts", "Luxury", "Chocolates", "Valentine", "Christmas"]
  },
  {
    id: "p-fluffy-marshmallow-clouds",
    name: "FLUFFY PINK & WHITE MARSHMALLOWS",
    category: "Marshmallows",
    mainCategory: "NZ Lollies",
    price: 2.99,
    rating: 4.7,
    reviewsCount: 31,
    description: "Super light, pillowy pink and white marshmallows. Perfect for hot chocolate mugs, campfire roasting, baking, or party candy bowls.",
    ingredients: "Sugar, Glucose Syrup, Invert Sugar, Water, Gelatine, Flavors, Color (120), Corn Starch.",
    nutrition: { calories: "110 kcal", sugar: "23g", fat: "0g", protein: "1g" },
    gradient: "linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%)",
    image: "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&q=80&w=600",
    images: ["https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&q=80&w=600"],
    inStock: true,
    quantity: 120,
    isPopular: false,
    isNew: false,
    collections: ["Parties", "Kids", "Marshmallows", "Sweet Treats"]
  },
  {
    id: "p-traditional-black-licorice",
    name: "TRADITIONAL SOFT-EATING BLACK LICORICE",
    category: "Licorice",
    mainCategory: "NZ Lollies",
    price: 6.49,
    rating: 4.8,
    reviewsCount: 27,
    description: "Authentic soft-eating traditional black licorice logs crafted with real licorice root extract and rich molasses. Pure chewy satisfaction.",
    ingredients: "Wheat Flour, Molasses, Glucose Syrup, Sugar, Treacle, Licorice Extract, Color (150d), Aniseed Oil, Salt.",
    nutrition: { calories: "135 kcal", sugar: "20g", fat: "0.8g", protein: "2g" },
    gradient: "linear-gradient(135deg, #232526 0%, #414345 100%)",
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?auto=format&fit=crop&q=80&w=600",
    images: ["https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?auto=format&fit=crop&q=80&w=600"],
    inStock: true,
    quantity: 90,
    isPopular: false,
    isNew: false,
    collections: ["NZ Favourites", "Licorice", "Kiwi Classics"]
  }
];

export const defaultTestimonials = [
  {
    name: 'Phoebe S. (Auckland)',
    role: 'Sweet Enthusiast',
    avatar: 'P',
    quote: 'Best Lolly Shop has the most amazing selection! The quality is unmatched and courier delivery within Auckland was overnight. My kids absolutely love their favourites!',
    rating: 5
  },
  {
    name: 'Rawiri K. (Wellington)',
    role: 'Regular Customer',
    avatar: 'R',
    quote: 'I\'ve ordered from many candy stores, but none compare to Best Lolly Shop. Fresh, delicious sweets, and beautifully packaged. Perfect for gifting in NZ!',
    rating: 5
  },
  {
    name: 'Alisha P. (Christchurch)',
    role: 'Party Planner',
    avatar: 'A',
    quote: 'Their bulk lollies for parties are fantastic! Great variety, competitive NZD prices, and the customer service is exceptional. Highly recommended!',
    rating: 5
  },
  {
    name: 'Val M. (Dunedin)',
    role: 'Chocolate Lover',
    avatar: 'V',
    quote: 'The chocolates are divine! Premium quality at reasonable prices. Best Lolly Shop is now my go-to for all sweet cravings in NZ.',
    rating: 5
  }
];
