export const initialBrands = [
  { name: 'Bazooka', color: '#00aeef', svgType: 'bazooka' },
  { name: 'Chupa Chups', color: '#e20613', svgType: 'chupachups' },
  { name: 'Hershey\'s', color: '#2a120e', svgType: 'hersheys' },
  { name: 'Reeses', color: '#f05a28', svgType: 'reeses' },
  { name: 'Walkers', color: '#ffffff', svgType: 'walkers' },
  { name: 'Warheads', color: '#4a2c81', svgType: 'warheads' }
];

export const defaultUsers = [
  { name: 'Sarah Jenkins', email: 'sarah.j@gmail.com', password: 'password123', role: 'user' },
  { name: 'Matthew Taylor', email: 'matthew.t@hotmail.co.nz', password: 'password123', role: 'user' },
  { name: 'Chloe Smith', email: 'chloe.s@gmail.com', password: 'password123', role: 'user' },
  { name: 'Liam Wilson', email: 'liam.wilson@yahoo.com', password: 'password123', role: 'user' },
  { name: 'Store Administrator', email: 'admin@lollyshop.co.nz', password: 'admin123', role: 'admin' },
  { name: 'John Doe', email: 'john@gmail.com', password: 'user123', role: 'user' }
];

export const initialProducts = [
  {
    name: 'Sour Neon Worms',
    category: 'Gummies',
    price: 8.50,
    rating: 4.8,
    reviewsCount: 124,
    description: 'Juicy, fruit-flavored sour worms dusted with a tangy sugar coating. Experience a burst of sour then sweet in every single bite.',
    ingredients: 'Sugar, Glucose Syrup, Modified Corn Starch, Gelatin, Citric Acid, Lactic Acid, Fumaric Acid, Natural and Artificial Flavors.',
    nutrition: { calories: '140 kcal', sugar: '26g', fat: '0g', protein: '1.2g' },
    gradient: 'linear-gradient(135deg, #FF3366 0%, #FF9933 100%)',
    image: 'https://images.unsplash.com/photo-1581798459219-318e76aecc7b?auto=format&fit=crop&q=80&w=600',
    inStock: true,
    isPopular: true,
    isNew: false,
    collections: ['Easter', 'Parties']
  },
  {
    name: 'Premium Dark Truffles',
    category: 'Chocolates',
    price: 16.90,
    rating: 4.9,
    reviewsCount: 88,
    description: 'Rich Belgian dark chocolate truffles with a silky smooth chocolate ganache center, dusted with premium cocoa powder.',
    ingredients: 'Dark Chocolate, Cocoa Butter, Sugar, Heavy Cream, Cocoa Powder, Soy Lecithin, Natural Vanilla Flavor.',
    nutrition: { calories: '210 kcal', sugar: '12g', fat: '14g', protein: '3g' },
    gradient: 'linear-gradient(135deg, #4A0E17 0%, #0F0C1B 100%)',
    image: 'https://images.unsplash.com/photo-1549007994-cb92ca818bc6?auto=format&fit=crop&q=80&w=600',
    inStock: true,
    isPopular: true,
    isNew: true,
    collections: ['Gift', 'Corporate Gifting']
  },
  {
    name: 'Rainbow Carousel Lollipop',
    category: 'Lollipops',
    price: 4.90,
    rating: 4.7,
    reviewsCount: 205,
    description: 'A classic gourmet swirl lollipop bursting with wild cherry and blue raspberry fruit flavors. Bright, colourful, and fun!',
    ingredients: 'Sugar, Corn Syrup, Citric Acid, Natural Cherry Flavor, Artificial Colors (Red 40, Blue 1, Yellow 5).',
    nutrition: { calories: '90 kcal', sugar: '22g', fat: '0g', protein: '0g' },
    gradient: 'linear-gradient(135deg, #00F2FE 0%, #4FACFE 100%)',
    image: 'https://images.unsplash.com/photo-1534080391025-a77af30d1a9e?auto=format&fit=crop&q=80&w=600',
    inStock: true,
    isPopular: true,
    isNew: false,
    collections: ['Parties', 'Birthday']
  },
  {
    name: 'Strawberry Fluff Clouds',
    category: 'Marshmallows',
    price: 6.50,
    rating: 4.6,
    reviewsCount: 64,
    description: 'Puffy, light-as-air strawberry marshmallows made with real fruit puree. Meltingly soft and delicious in hot cocoa or on their own.',
    ingredients: 'Sugar, Corn Syrup, Water, Strawberry Puree, Gelatin, Powdered Sugar, Natural Strawberry Extracts.',
    nutrition: { calories: '110 kcal', sugar: '19g', fat: '0g', protein: '1g' },
    gradient: 'linear-gradient(135deg, #FF758C 0%, #FF7EB3 100%)',
    image: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?auto=format&fit=crop&q=80&w=600',
    inStock: true,
    isPopular: false,
    isNew: true,
    collections: ['Baby Showers']
  },
  {
    name: 'Fuzzy Peach Rings',
    category: 'Gummies',
    price: 7.90,
    rating: 4.8,
    reviewsCount: 142,
    description: 'Perfectly chewy candy rings packed with intense sweet peach flavor and coated in a tangy sour crystalline sugar dusting.',
    ingredients: 'Sugar, Corn Syrup, Gelatin, Citric Acid, Peach Juice Concentrate, Fumaric Acid, Tartaric Acid, Natural Flavors.',
    nutrition: { calories: '130 kcal', sugar: '24g', fat: '0g', protein: '1g' },
    gradient: 'linear-gradient(135deg, #FF9966 0%, #FF5E62 100%)',
    image: 'https://images.unsplash.com/photo-1582293041079-7814c2f12063?auto=format&fit=crop&q=80&w=600',
    inStock: true,
    isPopular: false,
    isNew: false,
    collections: ['Valentine']
  },
  {
    name: 'Sea Salt Caramel Bar',
    category: 'Chocolates',
    price: 11.50,
    rating: 4.9,
    reviewsCount: 198,
    description: 'Creamy milk chocolate block loaded with pockets of gooey liquid gold caramel and sprinkled with fine French fleur de sel.',
    ingredients: 'Milk Chocolate, Caramel (Corn Syrup, Sweetened Condensed Milk, Butter, Cream), French Sea Salt, Soy Lecithin.',
    nutrition: { calories: '190 kcal', sugar: '18g', fat: '11g', protein: '2g' },
    gradient: 'linear-gradient(135deg, #FFE259 0%, #FFA751 100%)',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&q=80&w=600',
    inStock: true,
    isPopular: true,
    isNew: false,
    collections: ['Gift', 'Father']
  },
  {
    name: 'Blueberry Bubble Pop',
    category: 'Lollipops',
    price: 5.50,
    rating: 4.5,
    reviewsCount: 52,
    description: 'A vibrant blue lollipop with a juicy, long-lasting bubblegum core. Twice the fun, twice the sweet experience!',
    ingredients: 'Sugar, Gum Base, Glucose Syrup, Citric Acid, Blueberry Flavoring, Glycerin, FD&C Blue No. 1.',
    nutrition: { calories: '120 kcal', sugar: '25g', fat: '0g', protein: '0g' },
    gradient: 'linear-gradient(135deg, #1AD6FD 0%, #1D62F0 100%)',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=600',
    inStock: false,
    isPopular: false,
    isNew: true,
    collections: ['Parties']
  },
  {
    name: 'Toasted Coconut Mallows',
    category: 'Marshmallows',
    price: 7.50,
    rating: 4.7,
    reviewsCount: 76,
    description: 'Fluffy vanilla marshmallows rolled in slow-roasted, crunchy sweet shredded coconut flakes. A tropical candy escape.',
    ingredients: 'Sugar, Roasted Coconut Flakes, Water, Gelatin, Natural Vanilla Bean Extract, Potassium Sorbate.',
    nutrition: { calories: '150 kcal', sugar: '17g', fat: '4g', protein: '1g' },
    gradient: 'linear-gradient(135deg, #AB7A5F 0%, #E2D4C9 100%)',
    image: 'https://images.unsplash.com/photo-1536680465769-2365207b035e?auto=format&fit=crop&q=80&w=600',
    inStock: true,
    isPopular: false,
    isNew: false,
    collections: ['Gift']
  },
  {
    name: 'Easter Chocolate Eggs',
    category: 'Chocolates',
    price: 9.90,
    rating: 4.9,
    reviewsCount: 154,
    description: 'Creamy milk chocolate eggs wrapped in colorful foils. A sweet Easter classic for searches and holiday egg hunts.',
    ingredients: 'Sugar, Milk Solids, Cocoa Butter, Cocoa Mass, Lecithin, Natural Vanilla Extract.',
    nutrition: { calories: '160 kcal', sugar: '22g', fat: '10g', protein: '2g' },
    gradient: 'linear-gradient(135deg, #a8c0ff 0%, #3f2b96 100%)',
    image: 'https://images.unsplash.com/photo-1522336572468-97b06eca219b?auto=format&fit=crop&q=80&w=600',
    inStock: true,
    isPopular: true,
    isNew: false,
    collections: ['Easter']
  },
  {
    name: 'Spooky Gummy Skulls',
    category: 'Gummies',
    price: 6.90,
    rating: 4.8,
    reviewsCount: 92,
    description: 'Strawberry and grape flavored gummy skulls with a sour fizz coating. Ideal for Halloween treats.',
    ingredients: 'Sugar, Gelatin, Citric Acid, Tartaric Acid, Grape Juice Concentrate, Natural Purple Carrot Color.',
    nutrition: { calories: '130 kcal', sugar: '24g', fat: '0g', protein: '1g' },
    gradient: 'linear-gradient(135deg, #e65c00 0%, #f9d423 100%)',
    image: 'https://images.unsplash.com/photo-1508808789028-6a52a559fc43?auto=format&fit=crop&q=80&w=600',
    inStock: true,
    isPopular: false,
    isNew: false,
    collections: ['Halloween']
  },
  {
    name: 'Mint Candy Canes',
    category: 'Lollipops',
    price: 4.50,
    rating: 4.7,
    reviewsCount: 110,
    description: 'Traditional red and white candy canes infused with pure natural peppermint oil. A Christmas stock favorite.',
    ingredients: 'Sugar, Light Corn Syrup, Natural Peppermint Oil, Color (Titanium Dioxide, Red 40).',
    nutrition: { calories: '80 kcal', sugar: '20g', fat: '0g', protein: '0g' },
    gradient: 'linear-gradient(135deg, #F00000 0%, #BE93C5 100%)',
    image: 'https://images.unsplash.com/photo-1545601445-4d6a5a04d92e?auto=format&fit=crop&q=80&w=600',
    inStock: true,
    isPopular: false,
    isNew: false,
    collections: ['Christmas']
  },
  {
    name: 'British Royal Toffees',
    category: 'Chocolates',
    price: 12.50,
    rating: 4.8,
    reviewsCount: 43,
    description: 'Buttery English toffee blocks dipped in silky milk chocolate. Created to celebrate the King\'s Birthday.',
    ingredients: 'Sugar, Butter, Sweetened Condensed Milk, Cocoa Butter, Toffee Extracts, Salt.',
    nutrition: { calories: '180 kcal', sugar: '16g', fat: '12g', protein: '1.5g' },
    gradient: 'linear-gradient(135deg, #1f4037 0%, #99f2c8 100%)',
    image: 'https://images.unsplash.com/photo-1581798459219-318e76aecc7b?auto=format&fit=crop&q=80&w=600',
    inStock: true,
    isPopular: false,
    isNew: false,
    collections: ['Birthday']
  },
  {
    name: 'Matariki Star Gummies',
    category: 'Gummies',
    price: 8.90,
    rating: 4.9,
    reviewsCount: 78,
    description: 'Gold-dusted lemon and orange flavored star gummies. Celebrate the Māori New Year Matariki with stars.',
    ingredients: 'Sugar, Glucose, Gelatin, Citric Acid, Orange Juice, Edible Gold Dust, Natural Colors.',
    nutrition: { calories: '135 kcal', sugar: '25g', fat: '0g', protein: '1.2g' },
    gradient: 'linear-gradient(135deg, #0575E6 0%, #00F260 100%)',
    image: 'https://images.unsplash.com/photo-1534080391025-a77af30d1a9e?auto=format&fit=crop&q=80&w=600',
    inStock: true,
    isPopular: true,
    isNew: true,
    collections: ['Matariki']
  },
  {
    name: 'Sweetheart Gummy Hearts',
    category: 'Gummies',
    price: 7.90,
    rating: 4.8,
    reviewsCount: 231,
    description: 'Soft sugar-sanded gummy hearts with a deep cherry juice flavor. Celebrate Valentine\'s Day with love.',
    ingredients: 'Sugar, Corn Syrup, Gelatin, Cherry Juice, Citric Acid, Fumaric Acid, Natural Red Beet Color.',
    nutrition: { calories: '120 kcal', sugar: '23g', fat: '0g', protein: '1g' },
    gradient: 'linear-gradient(135deg, #ef32d9 0%, #89fffd 100%)',
    image: 'https://images.unsplash.com/photo-1582293041079-7814c2f12063?auto=format&fit=crop&q=80&w=600',
    inStock: true,
    isPopular: true,
    isNew: false,
    collections: ['Valentine']
  },
  {
    name: 'Lavender Honey Gumdrops',
    category: 'Gummies',
    price: 8.50,
    rating: 4.9,
    reviewsCount: 94,
    description: 'Gumdrops made with pure New Zealand clover honey and organic lavender extracts. A sweet Mother\'s Day treat.',
    ingredients: 'Sugar, Honey, Gelatin, Pectin, Lavender Extract, Natural Citrus Pectin, Citric Acid.',
    nutrition: { calories: '125 kcal', sugar: '22g', fat: '0g', protein: '1g' },
    gradient: 'linear-gradient(135deg, #83a4d4 0%, #b6fbff 100%)',
    image: 'https://images.unsplash.com/photo-1582293041079-7814c2f12063?auto=format&fit=crop&q=80&w=600',
    inStock: true,
    isPopular: false,
    isNew: false,
    collections: ['Mother']
  },
  {
    name: 'Smoky Maple Caramels',
    category: 'Chocolates',
    price: 14.90,
    rating: 4.8,
    reviewsCount: 65,
    description: 'Dark chocolate block infused with liquid smoky maple syrup and toffee shards. Made for Father\'s Day.',
    ingredients: 'Sugar, Dark Chocolate, Maple Syrup, Heavy Butter, Natural Caramel Flavors, Lecithin.',
    nutrition: { calories: '200 kcal', sugar: '15g', fat: '13g', protein: '2g' },
    gradient: 'linear-gradient(135deg, #4b6cb7 0%, #182848 100%)',
    image: 'https://images.unsplash.com/photo-1549007994-cb92ca818bc6?auto=format&fit=crop&q=80&w=600',
    inStock: true,
    isPopular: false,
    isNew: false,
    collections: ['Father']
  },
  {
    name: 'Pink Ribbon Gummy Hearts',
    category: 'Gummies',
    price: 5.90,
    rating: 4.7,
    reviewsCount: 112,
    description: 'Juicy strawberry ribbons and hearts. Supporting breast cancer campaigns on Pink Ribbon & Shirt Day.',
    ingredients: 'Sugar, Corn Syrup, Gelatin, Pectin, Strawberry Juice, Citric Acid, Red Radish Extract.',
    nutrition: { calories: '115 kcal', sugar: '21g', fat: '0g', protein: '1g' },
    gradient: 'linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%)',
    image: 'https://images.unsplash.com/photo-1582293041079-7814c2f12063?auto=format&fit=crop&q=80&w=600',
    inStock: true,
    isPopular: false,
    isNew: false,
    collections: ['Ribbon']
  },
  {
    name: 'Red Nose Cherry Drops',
    category: 'Lollipops',
    price: 4.90,
    rating: 4.8,
    reviewsCount: 83,
    description: 'Cherry hard candies shaped like red noses. Fun for kids and supporting Red Nose Day charity events.',
    ingredients: 'Sugar, Glucose, Cherry Juice, Citric Acid, Natural Cherry Extract, Carmine Color.',
    nutrition: { calories: '95 kcal', sugar: '24g', fat: '0g', protein: '0g' },
    gradient: 'linear-gradient(135deg, #f857a6 0%, #ff5858 100%)',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=600',
    inStock: true,
    isPopular: false,
    isNew: false,
    collections: ['Nose']
  },
  {
    name: 'Daffodil Yellow Gumdrops',
    category: 'Gummies',
    price: 6.90,
    rating: 4.9,
    reviewsCount: 149,
    description: 'Tart lemon gumdrops shaped like spring daffodils. Supporting Daffodil Day cancer awareness.',
    ingredients: 'Sugar, Pectin, Lemon Juice, Citric Acid, Turmeric Extract (for natural yellow color).',
    nutrition: { calories: '120 kcal', sugar: '23g', fat: '0g', protein: '0.8g' },
    gradient: 'linear-gradient(135deg, #f7ff00 0%, #dbd623 100%)',
    image: 'https://images.unsplash.com/photo-1582293041079-7814c2f12063?auto=format&fit=crop&q=80&w=600',
    inStock: true,
    isPopular: true,
    isNew: true,
    collections: ['Daffodil']
  },
  {
    name: 'Blue September Gummy Rings',
    category: 'Gummies',
    price: 7.50,
    rating: 4.7,
    reviewsCount: 68,
    description: 'Tangy blue raspberry rings. Ideal for events and supporting Blue September health awareness.',
    ingredients: 'Sugar, Gelatin, Citric Acid, Blue Raspberry Juice, Spirulina Extract (for natural blue color).',
    nutrition: { calories: '130 kcal', sugar: '25g', fat: '0g', protein: '1g' },
    gradient: 'linear-gradient(135deg, #00c6ff 0%, #0072ff 100%)',
    image: 'https://images.unsplash.com/photo-1582293041079-7814c2f12063?auto=format&fit=crop&q=80&w=600',
    inStock: true,
    isPopular: false,
    isNew: false,
    collections: ['September']
  },
  {
    name: 'Wedding Bells White Choc',
    category: 'Chocolates',
    price: 15.90,
    rating: 4.9,
    reviewsCount: 104,
    description: 'Silky Swiss white chocolate bells with a vanilla cream center. Perfect for weddings and anniversaries.',
    ingredients: 'Sugar, Cocoa Butter, Whole Milk Powder, Butterfat, Soy Lecithin, Madagascan Vanilla Extract.',
    nutrition: { calories: '220 kcal', sugar: '14g', fat: '16g', protein: '3.2g' },
    gradient: 'linear-gradient(135deg, #ECE9E6 0%, #FFFFFF 100%)',
    image: 'https://images.unsplash.com/photo-1549007994-cb92ca818bc6?auto=format&fit=crop&q=80&w=600',
    inStock: true,
    isPopular: true,
    isNew: false,
    collections: ['Wedding']
  },
  {
    name: 'Baby Clouds Fluffs',
    category: 'Marshmallows',
    price: 6.50,
    rating: 4.8,
    reviewsCount: 157,
    description: 'Super-soft pastel pink and blue vanilla marshmallows. A sweet hit for baby showers and birthday parties.',
    ingredients: 'Sugar, Corn Syrup, Gelatin, Vanilla Flavor, Red Beet Extract, Spirulina Concentrate.',
    nutrition: { calories: '110 kcal', sugar: '19g', fat: '0g', protein: '1g' },
    gradient: 'linear-gradient(135deg, #a1c4fd 0%, #c2e9fb 100%)',
    image: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?auto=format&fit=crop&q=80&w=600',
    inStock: true,
    isPopular: true,
    isNew: true,
    collections: ['Baby']
  },
  {
    name: 'Lucky Clover Gummies',
    category: 'Gummies',
    price: 6.90,
    rating: 4.7,
    reviewsCount: 42,
    description: 'Sour apple four-leaf clovers. Bring green luck to your celebrations and St Patrick\'s Day parties.',
    ingredients: 'Sugar, Glucose, Gelatin, Apple Concentrates, Citric Acid, Safflower Extract, Blue Spirulina.',
    nutrition: { calories: '125 kcal', sugar: '23g', fat: '0g', protein: '1.2g' },
    gradient: 'linear-gradient(135deg, #11998e 0%, #38ef7d 100%)',
    image: 'https://images.unsplash.com/photo-1582293041079-7814c2f12063?auto=format&fit=crop&q=80&w=600',
    inStock: true,
    isPopular: false,
    isNew: false,
    collections: ['Patrick']
  },
  {
    name: 'Gourmet Sweet Gift Box',
    category: 'Marshmallows',
    price: 24.90,
    rating: 4.9,
    reviewsCount: 184,
    description: 'Assorted gourmet chocolates, marshmallows and gummies in a beautiful luxury box. A premium gifting idea.',
    ingredients: 'Sugar, Cocoa Butter, Milk Powder, Gelatin, Assorted Fruit Juices, Pectin, Lavender, Rose Extract.',
    nutrition: { calories: '190 kcal', sugar: '20g', fat: '8g', protein: '2g' },
    gradient: 'linear-gradient(135deg, #fbc2eb 0%, #a6c1ee 100%)',
    image: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?auto=format&fit=crop&q=80&w=600',
    inStock: true,
    isPopular: true,
    isNew: false,
    collections: ['Gift']
  },
  
  // ── NEW PRODUCTS ADDED FOR ATLAS/FALLBACK DATABASE ──
  {
    name: 'Sour Apple Belts',
    category: 'Gummies',
    price: 6.90,
    rating: 4.8,
    reviewsCount: 45,
    description: 'Tangy green apple flavored gummy belts dusted with a mouth-puckering crystalline sour sugar layer.',
    ingredients: 'Sugar, Glucose-Fructose Syrup, Wheat Flour, Malic Acid, Dextrose, Palm Oil, Citric Acid, Artificial Flavor, FD&C Yellow 5, Blue 1.',
    nutrition: { calories: '140 kcal', sugar: '22g', fat: '1g', protein: '0g' },
    gradient: 'linear-gradient(135deg, #8ae88a 0%, #2ea82e 100%)',
    image: 'https://images.unsplash.com/photo-1581798459219-318e76aecc7b?auto=format&fit=crop&q=80&w=600',
    inStock: true,
    isPopular: false,
    isNew: true,
    collections: ['Parties', 'Sour']
  },
  {
    name: 'Jelly Beans Mix',
    category: 'Gummies',
    price: 5.90,
    rating: 4.6,
    reviewsCount: 71,
    description: 'A colorful mix of gourmet jelly beans, including cherry, blueberry, lemon, lime, and orange fruit flavors.',
    ingredients: 'Sugar, Glucose Syrup, Modified Starch, Acids (Malic, Citric), Glazing Agents (Shellac, Carnauba Wax), Flavorings, Colors.',
    nutrition: { calories: '150 kcal', sugar: '28g', fat: '0g', protein: '0g' },
    gradient: 'linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%)',
    image: 'https://images.unsplash.com/photo-1582293041079-7814c2f12063?auto=format&fit=crop&q=80&w=600',
    inStock: true,
    isPopular: true,
    isNew: false,
    collections: ['Parties', 'Easter']
  },
  {
    name: 'Salted Caramel Fudge',
    category: 'Chocolates',
    price: 12.90,
    rating: 4.9,
    reviewsCount: 39,
    description: 'Rich, melt-in-your-mouth butter fudge blocks infused with sea salt crystals and premium maple sugar.',
    ingredients: 'Sugar, Sweetened Condensed Milk, Butter, Golden Syrup, Sea Salt, Natural Caramel Flavor.',
    nutrition: { calories: '210 kcal', sugar: '25g', fat: '9g', protein: '1g' },
    gradient: 'linear-gradient(135deg, #FFE259 0%, #FFA751 100%)',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&q=80&w=600',
    inStock: true,
    isPopular: false,
    isNew: true,
    collections: ['Gift', 'Fudge']
  },
  {
    name: 'Strawberry Licorice Twists',
    category: 'Gummies',
    price: 7.20,
    rating: 4.7,
    reviewsCount: 55,
    description: 'Soft and chewy classic red licorice twists infused with concentrated natural strawberry juices.',
    ingredients: 'Enriched Wheat Flour, Sugar, Corn Syrup, Water, Strawberry Juice, Glycerin, Artificial Flavor, Red 40.',
    nutrition: { calories: '130 kcal', sugar: '19g', fat: '0.5g', protein: '1g' },
    gradient: 'linear-gradient(135deg, #ff758c 0%, #ff7eb3 100%)',
    image: 'https://images.unsplash.com/photo-1581798459219-318e76aecc7b?auto=format&fit=crop&q=80&w=600',
    inStock: true,
    isPopular: false,
    isNew: false,
    collections: ['Parties']
  },
  {
    name: 'Raspberry Sherbet Bombs',
    category: 'Lollipops',
    price: 4.80,
    rating: 4.5,
    reviewsCount: 33,
    description: 'Classic hard boiled raspberry drops filled with a fizzy sherbet center. A vintage Kiwi favorite!',
    ingredients: 'Sugar, Glucose Syrup, Citric Acid, Sodium Bicarbonate, Flavorings, Natural Colors.',
    nutrition: { calories: '90 kcal', sugar: '23g', fat: '0g', protein: '0g' },
    gradient: 'linear-gradient(135deg, #f857a6 0%, #ff5858 100%)',
    image: 'https://images.unsplash.com/photo-1534080391025-a77af30d1a9e?auto=format&fit=crop&q=80&w=600',
    inStock: true,
    isPopular: true,
    isNew: false,
    collections: ['Retro', 'Fizzy']
  },
  {
    name: 'Toffee Apple Pop',
    category: 'Lollipops',
    price: 5.20,
    rating: 4.6,
    reviewsCount: 28,
    description: 'A delicious double-layered lollipop featuring tart green apple candy coated in rich, buttery caramel.',
    ingredients: 'Sugar, Glucose Syrup, Citric Acid, Butter, Milk solids, Natural Apple Flavor, Color (E141, E150).',
    nutrition: { calories: '95 kcal', sugar: '22g', fat: '0.8g', protein: '0g' },
    gradient: 'linear-gradient(135deg, #0575E6 0%, #00F260 100%)',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=600',
    inStock: true,
    isPopular: false,
    isNew: true,
    collections: ['Autumn']
  }
];

export const defaultTestimonials = [
  {
    name: 'Priya Sharma',
    role: 'Sweet Enthusiast',
    avatar: 'P',
    quote: 'Best Lolly Shop has the most amazing collection! The quality is unmatched and delivery is always on time. My kids absolutely love their gummies!',
    rating: 5
  },
  {
    name: 'Rajesh Kumar',
    role: 'Regular Customer',
    avatar: 'R',
    quote: 'I\'ve ordered from many candy stores, but none compare to Best Lolly Shop. Fresh, delicious, and beautifully packaged. Perfect for gifting!',
    rating: 5
  },
  {
    name: 'Anita Patel',
    role: 'Party Planner',
    avatar: 'A',
    quote: 'Their bulk orders for parties are fantastic! Great variety, competitive prices, and the customer service is exceptional. Highly recommended!',
    rating: 5
  },
  {
    name: 'Vikram Singh',
    role: 'Chocolate Lover',
    avatar: 'V',
    quote: 'The chocolates are divine! Premium quality at reasonable prices. Best Lolly Shop is now my go-to for all sweet cravings.',
    rating: 5
  }
];
